// <auto-generated />
using System;
using EjustLostAndFoundHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EjustLostAndFoundHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260714132026_AddContactEmail")]
    partial class AddContactEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EjustLostAndFoundHub.Models.ItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateReported")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationFound")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EjustLostAndFoundHub.Models.DeviceItem", b =>
                {
                    b.HasBaseType("EjustLostAndFoundHub.Models.ItemModel");

                    b.Property<string>("DeviceBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DeviceItems", (string)null);
                });

            modelBuilder.Entity("EjustLostAndFoundHub.Models.IdItem", b =>
                {
                    b.HasBaseType("EjustLostAndFoundHub.Models.ItemModel");

                    b.Property<string>("IdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("IdItems", (string)null);
                });

            modelBuilder.Entity("EjustLostAndFoundHub.Models.JewelryItem", b =>
                {
                    b.HasBaseType("EjustLostAndFoundHub.Models.ItemModel");

                    b.Property<string>("JewelryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JewelryMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JewelryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("JewelryItems", (string)null);
                });

            modelBuilder.Entity("EjustLostAndFoundHub.Models.NotebookItem", b =>
                {
                    b.HasBaseType("EjustLostAndFoundHub.Models.ItemModel");

                    b.Property<string>("NotebookColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotebookDescription")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("NotebookItems", (string)null);
                });

            modelBuilder.Entity("EjustLostAndFoundHub.Models.WalletItem", b =>
                {
                    b.HasBaseType("EjustLostAndFoundHub.Models.ItemModel");

                    b.Property<string>("WalletBrandOrMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WalletColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WalletDescription")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("WalletItems", (string)null);
                });

            modelBuilder.Entity("EjustLostAndFoundHub.Models.DeviceItem", b =>
                {
                    b.HasOne("EjustLostAndFoundHub.Models.ItemModel", null)
                        .WithOne()
                        .HasForeignKey("EjustLostAndFoundHub.Models.DeviceItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EjustLostAndFoundHub.Models.IdItem", b =>
                {
                    b.HasOne("EjustLostAndFoundHub.Models.ItemModel", null)
                        .WithOne()
                        .HasForeignKey("EjustLostAndFoundHub.Models.IdItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EjustLostAndFoundHub.Models.JewelryItem", b =>
                {
                    b.HasOne("EjustLostAndFoundHub.Models.ItemModel", null)
                        .WithOne()
                        .HasForeignKey("EjustLostAndFoundHub.Models.JewelryItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EjustLostAndFoundHub.Models.NotebookItem", b =>
                {
                    b.HasOne("EjustLostAndFoundHub.Models.ItemModel", null)
                        .WithOne()
                        .HasForeignKey("EjustLostAndFoundHub.Models.NotebookItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EjustLostAndFoundHub.Models.WalletItem", b =>
                {
                    b.HasOne("EjustLostAndFoundHub.Models.ItemModel", null)
                        .WithOne()
                        .HasForeignKey("EjustLostAndFoundHub.Models.WalletItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
